
name: envsubst
description: This is an action to go thtough all YAML files in repos ./kube/base folder, and change variables
inputs:
  patterns:
    description: Restrict the substitution to a strict set of patterns.
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        FILES=(./kube/base/*)
        for FILE in $FILES; do
          if [[ -n $PATTERNS ]] ; then
            envsubst "${PATTERNS}" < $FILE > /tmp/envsubst || exit 1
          else
            envsubst < $FILE > /tmp/envsubst || exit 1
          fi
          mv /tmp/envsubst $FILE || exit 1
        done
      shell: bash
      env:
        FILES: ${{ inputs.files }}
        PATTERNS: ${{ inputs.patterns }}