name: "Deploy to dev k8s"

on:
  workflow_call:

    inputs:
      SLACK_BOT_TOKEN:
        type: string
        required: true
        description: 'Token for Slack-bot'
      SLACK_DEV_DEPLOY_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-deploy-dev ID'
      NAMESPACE:
        type: string
        required: true
        description: 'Namespace in the cluster'
      KUSTOMIZE_OVERLAY:
        type: string
        required: true
        description: 'Path to Kustomize overlay'
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true

jobs:  
  deploy_dev:
    runs-on: small-runner
    outputs:
      SLACK_MESSAGE_ID: ${{ steps.gh-deploy-dev.outputs.message_id }}
      TAG: ${{ env.TAG }}
    steps:
      - name: Set environment variables
        id: envs 
        run: |
          TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`
          echo "TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      
      - name: Install envsubst 
        run: |
          apk update && apk add gettext

      - name: Notify Slack of Deploy
        id: gh-deploy-dev
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          status: Deploying ${{ env.TAG }} on Dev
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Inject image tag into files
        uses: SwipeStoxGmbH/reusable-workflows/actions/envsubst@v1.20
        with:
          patterns: $TAG
        env:
          TAG: ${{ env.TAG }}

      # - name: Build tag Substitution Start
      #   uses: danielr1996/envsubst-action@1.0.0
      #   with:
      #     input: ./kube/base/deployment.yaml
      #     output: ./kube/base/deployment-tagged.yaml

      # - name: Build Tag Substitution Finish
      #   run: |
      #     cat ./kube/base/deployment-tagged.yaml
      #     mv ./kube/base/deployment-tagged.yaml ./kube/base/deployment.yaml
          
      - name: Deploy
        uses: SwipeStoxGmbH/reusable-workflows/actions/deploy@v0.21
        with:
          NAMESPACE: ${{ inputs.NAMESPACE }}
          KUSTOMIZE_OVERLAY: ${{ inputs.KUSTOMIZE_OVERLAY }}

  slack_report_success:
    runs-on: small-runner
    needs: [deploy_dev]
    if: success()
    steps: 
      - name: Notify Slack of Success
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          message_id: ${{ needs.deploy_dev.outputs.slack_message_id }}
          status: ${{ needs.deploy_dev.outputs.TAG }} Dev Deployment Completed
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }} 

  slack_report_fail:
    runs-on: small-runner
    needs: [deploy_dev]
    if: failure()
    steps: 
      - name: Notify Slack of Failure
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          message_id: ${{ needs.deploy_dev.outputs.slack_message_id }}
          status: ${{ needs.deploy_dev.outputs.TAG }} Dev Deployment Failed
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }} 