name: "Deploy to production k8s"

on:
  workflow_call:

    inputs:
      SLACK_BOT_TOKEN:
        type: string
        required: true
        description: 'Token for Slack-bot'
      SLACK_PROD_DEPLOY_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-deploy-prod ID'
      NAMESPACE:
        type: string
        required: true
        description: 'Namespace in the cluster'
      KUSTOMIZE_OVERLAY:
        type: string
        required: true
        description: 'Path to Kustomize overlay'
      IMAGE_TAG:
        type: string
        required: true
        description: 'Image tag to deploy'
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true

jobs:  
  deploy_production:
    runs-on: small-prod-runner
    outputs:
      SLACK_MESSAGE_ID: ${{ steps.gh-deploy-prod.outputs.message_id }}
    steps:
      - name: Notify Slack of Production Deploy
        id: gh-deploy-prod
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_PROD_DEPLOY_CHANNEL_ID }}
          status: Deploying ${{ inputs.IMAGE_TAG }} on Production
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }} 

      - name: Checkout
        uses: actions/checkout@v1

      - name: Set environment variables
        run: |
          echo "TAG=${{ inputs.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Build tag Substitution Start
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: ./kube/base/deployment.yaml
          output: ./kube/base/deployment-tagged.yaml

      - name: Build Tag Substitution Finish
        run: |
          cat ./kube/base/deployment-tagged.yaml
          mv ./kube/base/deployment-tagged.yaml ./kube/base/deployment.yaml
          
      - name: Deploy
        uses: SwipeStoxGmbH/reusable-workflows/actions/deploy@v0.21
        with:
          NAMESPACE: ${{ inputs.NAMESPACE }}
          KUSTOMIZE_OVERLAY: ${{ inputs.KUSTOMIZE_OVERLAY }}

  slack_report_success:
    runs-on: small-runner
    needs: [deploy_production]
    if: success()
    steps: 
      - name: Notify Slack of Success
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_PROD_DEPLOY_CHANNEL_ID }}
          message_id: ${{ needs.deploy_production.outputs.slack_message_id }}
          status: ${{ env.TAG }} Production Deployment Completed
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }} 

  slack_report_fail:
    runs-on: small-runner
    needs: [deploy_production]
    if: failure()
    steps: 
      - name: Notify Slack of Failure
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_PROD_DEPLOY_CHANNEL_ID }}
          message_id: ${{ needs.deploy_production.outputs.slack_message_id }}
          status: ${{ env.TAG }} Production Deployment Failed
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }} 


