name: "Deploy to Production k8s"

on:
  workflow_call:

    inputs:
      SLACK_BOT_TOKEN:
        type: string
        required: true
        description: 'Token for Slack-bot'
      SLACK_CHANNEL_ID:
        type: string
        required: true
        description: 'ID of the Slack channel'
      SLACK_MESSAGE_ID:
        type: string
        required: true
        description: 'ID of the Slack message'
      NAMESPACE:
        type: string
        required: true
        description: 'Namespace in the cluster'
      KUSTOMIZE_OVERLAY:
        type: string
        required: true
        description: 'Path to Kustomize overlay'
      IMAGE_TAG:
        type: string
        required: true
        description: 'Image tag to deploy'
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true

jobs:  
  deploy:
    runs-on: small-prod-runner
    steps:
      - name: Notify Slack of Production Deploy
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_MESSAGE_ID }}
          status: Running ${{ github.job }} - Production Deploy ...
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }} 

      - name: Checkout
        uses: actions/checkout@v1

      - name: Set environment variables
        run: |
          echo "TAG=${{ inputs.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Build tag Substitution Start
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: ./kube/base/deployment.yaml
          output: ./kube/base/deployment-tagged.yaml

      - name: Build Tag Substitution Finish
        run: |
          cat ./kube/base/deployment-tagged.yaml
          mv ./kube/base/deployment-tagged.yaml ./kube/base/deployment.yaml
          
      - name: Deploy
        uses: SwipeStoxGmbH/reusable-workflows/actions/deploy@v0.21
        with:
          NAMESPACE: ${{ inputs.NAMESPACE }}
          KUSTOMIZE_OVERLAY: ${{ inputs.KUSTOMIZE_OVERLAY }}

