name: "Deploy to dev k8s"

on:
  workflow_call:

    inputs:
      SLACK_DEV_DEPLOY_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-deploy-dev ID'
      NAMESPACE:
        type: string
        required: true
        description: 'Namespace in the cluster'
      KUSTOMIZE_OVERLAY:
        type: string
        required: true
        description: 'Path to Kustomize overlay'
      KUSTOMIZE_BASE:
        type: string
        required: true
        description: 'Path to Kustomize base'
      CF_DISTRIBUTION_ID:
        type: string
        required: true
        description: 'CloudFront distribution ID'
      CF_INVALIDATION_PATHS:
        type: string
        required: true
        description: 'CloudFront invalidations paths'
    secrets:
      slack-bot-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true

jobs:  
  deploy_dev:
    runs-on: small-runner
    outputs:
      SLACK_MESSAGE_ID: ${{ steps.gh-deploy-dev.outputs.message_id }}
      TAG: ${{ env.TAG }}
    steps:
      - name: Set environment variables
        id: envs 
        run: |
          TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`
          echo "TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Notify Slack of Deploy
        id: gh-deploy-dev
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          status: Deploying ${{ env.TAG }} on Dev
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Inject image tag into files
        run: |
          sudo apt-get update -y
          sudo apt-get install gettext -y
          FILES=(${{ inputs.KUSTOMIZE_BASE }}/base/* ${{ inputs.KUSTOMIZE_BASE }}/overlays/dev/*)
          for FILE in ${FILES[@]}; do
            if [[ -n ${PATTERN} ]] ; then
              envsubst "${PATTERN}" < $FILE > /tmp/envsubst || exit 1
            else
              envsubst < $FILE > /tmp/envsubst || exit 1
            fi
            mv /tmp/envsubst $FILE || exit 1
          done
        env:
          PATTERN: $TAG 
          
      - name: Deploy
        uses: SwipeStoxGmbH/reusable-workflows/actions/deploy@master
        with:
          NAMESPACE: ${{ inputs.NAMESPACE }}
          KUSTOMIZE_OVERLAY: ${{ inputs.KUSTOMIZE_OVERLAY }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        if: ${{ inputs.CF_DISTRIBUTION_ID != '' && inputs.CF_INVALIDATION_PATHS != '' }}
        env:
          DISTRIBUTION: ${{ inputs.CF_DISTRIBUTION_ID }}
          PATHS: ${{ inputs.CF_INVALIDATION_PATHS }}
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}

  slack_report_success:
    runs-on: small-runner
    needs: [deploy_dev]
    if: success()
    steps: 
      - name: Notify Slack of Success
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          message_id: ${{ needs.deploy_dev.outputs.slack_message_id }}
          status: ${{ needs.deploy_dev.outputs.TAG }} Dev Deployment Completed
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 

  slack_report_fail:
    runs-on: small-runner
    needs: [deploy_dev]
    if: failure()
    steps: 
      - name: Notify Slack of Failure
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
          message_id: ${{ needs.deploy_dev.outputs.slack_message_id }}
          status: ${{ needs.deploy_dev.outputs.TAG }} Dev Deployment Failed
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 