name: "Tag release and push tag"

on:
  workflow_call:

    inputs:
      SLACK_BUILD_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-build - ID'
      SLACK_BUILD_MESSAGE_ID:
        type: string
        required: true
        description: '#gh-build - Message ID'
    secrets:
      slack-bot-token:
        required: true
      gh-token:
        required: true
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true

jobs:  
  git_tag:
    runs-on: small-runner
    outputs:
      TAG: ${{ env.TAG }}
      GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
      
    steps:
      - name: Set environment variables
        id: envs 
        run: |
          TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`
          echo "TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Checkout
        uses: actions/checkout@v1

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.TAG }}
          message: ${{ env.TAG }}

  