name: "Tag release and push tag"

on:
  workflow_call:

    inputs:
      SLACK_BUILD_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-build - ID'
      SLACK_BUILD_MESSAGE_ID:
        type: string
        required: true
        description: '#gh-build - Message ID'
    secrets:
      slack-bot-token:
        required: true
      gh-token:
        required: true

jobs:  
  git_tag:
    runs-on: small-runner
    outputs:
      SLACK_MESSAGE_ID: ${{ steps.gh-tag-slack.outputs.message_id }}
      TAG: ${{ env.TAG }}
    steps:
      - name: Extract TAG
        id: envs 
        run: |
          TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`
          echo "TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v1
 
      - name: Notify Slack of GH Tag
        id: gh-tag-slack
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
          status: Adding ${{ env.TAG }} tag on git
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Tag version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.gh-token }}
          custom_tag: ${{ env.TAG }}
          tag_prefix: ""

  slack_report_success:
    runs-on: small-runner
    needs: [git_tag]
    if: success()
    steps: 
      - name: Notify Slack of Success
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
          status: Build completed, git tag ${{ env.TAG }} created. 
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 

  slack_report_fail:
    runs-on: small-runner
    needs: [git_tag]
    if: failure()
    steps: 
      - name: Notify Slack of Failure
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
          status: Build completed, git tag ${{ env.TAG }} is NOT created 
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 

  