name: 'NGINX conf test'

on:
  workflow_call:

    inputs:
      SLACK_BUILD_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-build - ID'
      SLACK_BUILD_MESSAGE_ID:
        type: string
        required: true
        description: '#gh-build - Message ID'
      KUSTOMIZE_ROOT:
        type: string
        required: true
        description: 'Path to Kustomize base'
      KUSTOMIZE_OVERLAY:
        type: string
        required: true
        description: 'Path to Kustomize base'
      NGINX_IMAGE:
        type: string
        required: true
        description: 'NGINX Image'
      NGINX_CONFIG_FILES_PATH:
        type: string
        required: true
        description: 'NGINX Image'
      NGINX_CONFIG_FILES_EXPORT:
        type: string
        required: true
        description: 'NGINX Image'
    secrets:
      slack-bot-token:
        required: true


jobs:
  nginx_test:
    runs-on: small-runner
    steps:
    - name: Notify Slack of Test
      id: gh-build
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
        message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
        status: Testing NGINX Config
        color: B14736
      env:
        SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Running Tests
      uses: SwipeStoxGmbH/reusable-workflows/actions/nginx-test@master
      with:
        NGINX_CONFIG_FILES_PATH: ${{ inputs.NGINX_CONFIG_FILES_PATH }}
        NGINX_CONFIG_FILES_EXPORT: ${{ inputs.NGINX_CONFIG_FILES_EXPORT }}
        NGINX_IMAGE: ${{ inputs.NGINX_IMAGE }}

  report_success:
    runs-on: small-runner
    needs: [nginx_test]
    if: success()
    steps: 
      - name: Notify Slack of Success
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
          status: NGINX test passed
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

  report_fail:
    runs-on: small-runner
    needs: [nginx_test]
    if: failure()
    steps: 
      - name: Notify Slack of Failure
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
          status: NGINX test failed
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}
