name: 'Vulnerability scanning'

on:
  workflow_call:

    inputs:
      SLACK_BUILD_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-build - ID'
      SLACK_BUILD_MESSAGE_ID:
        type: string
        required: true
        description: '#gh-build - Message ID'
      ECR_REPO:
        type: string
        required: true
        description: 'Elastic Container Repository of the service'
      ECR_CACHE_REPO:
        type: string
        required: true
        description: 'Caching Elastic Container Repository of the service'
    secrets:
      slack-bot-token:
        required: true

jobs:
  vulnerability_scan:
    runs-on: small-runner
    outputs:
      TAG: ${{ env.TAG }}
    steps:

      - name: Set environment variables
        run: |
          echo "SHORT_COMMIT=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Notify Slack of Scan
        id: gh-build
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
          status: Scanning container image
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ inputs.ECR_REPO }}: ${{ env.TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  report_success:
    runs-on: small-runner
    needs: [vulnerability_scan]
    if: success()
    steps: 
      - name: Notify Slack of Success
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
          status: Vulnerability scan for ${{ needs.needs.vulnerability_scan.outputs.TAG }} passed
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

  report_fail:
    runs-on: small-runner
    needs: [vulnerability_scan]
    if: failure()
    steps: 
      - name: Notify Slack of Failure
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
          status: Vulnerability scan for ${{ needs.needs.vulnerability_scan.outputs.TAG }} failed
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}